### ISSUE TITLE
Assemblies in /lib/ don't match current version.

### ISSUE THREAD

**Issue by novakda** [tabbles/tabbles-testPlugin-ApiV4#1]
**Description**
As of commit f5b14887aaad84e068c8854aee01800d9375659e, the Dlls in /lib are out of date.  Tabbles Beta 4.1.22 and current Confidential will fail to load the plugin and Plugins menu remains empty.

**Notes**
Fixable by copying or refrencing DLLs from the installed program, but you may want to update the /lib/ versions to match.  I only realized the problem after using .NET Dependency Walker, checking the logs in %AppData\Tabbles and monitoring the load with Fuslogvw.exe (Assembly Binding Log Viewer).

**Suggested Resolution**
Include the up-to-date DLLS in the repository so users wanting to test the plugin can do so without recompiling.

**Comment by Andrea-Tabbles** [comment]
Hi Dan,

that has been taken care of!

**Comment by andrea-dintino** [comment]
@novakda, we fixed this now for real: the dlls should be copied from the Tabbles/Confidential folders. We're looking for a better long term solution for that.
